language: node_js
node_js:
  - 9
  - 8
script:
  - sudo npm i -g npm@latest && npm ci
  - npm install --global rollup
  - npm test -- --collectCoverage=true
  - npm run coveralls
deploy:
  provider: npm
  email: NPM_EMAIL
  api_key: NPM_TOKEN
  on:
    all_branches: true