language: node_js
node_js:
  - 8
cache:	
  directories:	
    - node_modules
script:
  - nnpm ci
  - npm install --global rollup
  - npm test -- --collectCoverage=true
  - npm run coveralls
addons:	
  artifacts: true
deploy:
  provider: npm
  email: NPM_EMAIL
  api_key: NPM_TOKEN
  on:
    all_branches: true