language: node_js
node_js:
  - 9
  - 8
cache:
  directories:
    - node_modules
script:
  - npm test -- --collectCoverage=true
  - npm run build
  - npm run coveralls
addons:
  artifacts: true
deploy:
  provider: npm
  email: NPM_EMAIL
  api_key: NPM_TOKEN
  on:
    branch: master